name: Build, Push to ECR, and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set image tag
        id: vars
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Tag and Push images to ECR
        run: |
          SERVICES=("backend_rds" "backend_redis")
          for SERVICE in "${SERVICES[@]}"; do
            docker build --no-cache -t ${SERVICE}:latest ./${SERVICE}
            docker tag ${SERVICE}:latest ${{ secrets.ECR_REPOSITORY_URI }}/${SERVICE}:${{ env.IMAGE_TAG }}
            docker push ${{ secrets.ECR_REPOSITORY_URI }}/${SERVICE}:${{ env.IMAGE_TAG }}
            docker tag ${SERVICE}:latest ${{ secrets.ECR_REPOSITORY_URI }}/${SERVICE}:latest
            docker push ${{ secrets.ECR_REPOSITORY_URI }}/${SERVICE}:latest
          done

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem

      - name: Deploy on EC2
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem docker-compose.yaml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/docker-compose.yaml
  
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          
          aws ecr get-login-password --region {{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}
          
          # Удаление кэша Docker
          docker system prune -a --volumes -f
          
          cd /home/ubuntu
          docker-compose pull
          docker-compose up -d
          EOF
