name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY_RDS: backend_rds
      ECR_REPOSITORY_REDIS: backend_redis

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set ECR_REGISTRY
        run: echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build backend_rds image
        run: |
          IMAGE_TAG=${{ env.commit_hash }}-${{ env.timestamp }}
          docker build -t ${{ env.ECR_REPOSITORY_RDS }}:$IMAGE_TAG -f backend_rds/Dockerfile backend_rds

      - name: Tag and push backend_rds to ECR
        run: |
          IMAGE_TAG=${{ env.commit_hash }}-${{ env.timestamp }}
          docker tag ${{ env.ECR_REPOSITORY_RDS }}:$IMAGE_TAG ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_RDS }}:$IMAGE_TAG
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_RDS }}:$IMAGE_TAG

      - name: Build backend_redis image
        run: |
          IMAGE_TAG=${{ env.commit_hash }}-${{ env.timestamp }}
          docker build -t ${{ env.ECR_REPOSITORY_REDIS }}:$IMAGE_TAG -f backend_redis/Dockerfile backend_redis

      - name: Tag and push backend_redis to ECR
        run: |
          IMAGE_TAG=${{ env.commit_hash }}-${{ env.timestamp }}
          docker tag ${{ env.ECR_REPOSITORY_REDIS }}:$IMAGE_TAG ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_REDIS }}:$IMAGE_TAG
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_REDIS }}:$IMAGE_TAG
