name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build backend_rds image
        run: |
          docker-compose -f docker-compose.yml build backend_rds

      - name: Tag and push backend_rds to ECR
        run: |
          docker tag backend_rds:latest ${{ secrets.ECR_REPOSITORY_URI }}/backend_rds:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/backend_rds:latest

      - name: Build backend_redis image
        run: |
          docker-compose -f docker-compose.yml build backend_redis

      - name: Tag and push backend_redis to ECR
        run: |
          docker tag backend_redis:latest ${{ secrets.ECR_REPOSITORY_URI }}/backend_redis:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/backend_redis:latest
